version: "3"

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    ports:
      - 8096:8096
    environment:
      - TZ=America/Santiago
    volumes:
      - ${MEDIA_STORAGE}:/media
      - ${JF_CONFIG}:/config
      - ${JF_CACHE}:/cache

  transmission:
    image: linuxserver/transmission
    restart: unless-stopped
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    environment:
      - TZ=America/Santiago
    expose:
      - 9091
    volumes:
      - ${MEDIA_STORAGE}:/media
      - ${TRN_CONFIG}:/config
      - ${TORRENT_STORAGE}:/downloads

  flexget:
    image: wiserain/flexget
    restart: unless-stopped
    ports:
      - 5050:5050
    environment:
      - TZ=America/Santiago
      - TORRENT_PLUGIN=transmission
      - FG_WEBUI_PASSWD=123456
    volumes:
      - ${FG_CONFIG}:/config
      - ${TORRENT_STORAGE}:/downloads
    links:
      - transmission
