version: "3"

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    ports:
      - 8096:8096
    environment:
      - TZ=America/Santiago
    volumes:
      - ${MEDIA_STORAGE}:/media
      - ${JF_CONFIG}:/config
      - ${JF_CACHE}:/cache

  transmission:
    image: linuxserver/transmission
    command: transmission-daemon -f -g /config
    restart: unless-stopped
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    environment:
      - TZ=America/Santiago
    volumes:
      - ./transmission:/config
      - ${TORRENT_STORAGE}:/downloads

  flexget:
    image: wiserain/flexget:3.3.4
    restart: unless-stopped
    ports:
      - 5050:5050
    expose:
      - 5050
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Santiago
      - TORRENT_PLUGIN=transmission
      - FG_WEBUI_PASSWD=${FG_PASS}
    volumes:
      - ./flexget:/config
      - ${TORRENT_STORAGE}:/downloads
      - ${MEDIA_STORAGE}:/media
    links:
      - transmission
