version: '2'

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: always
    ports:
      - 8096:8096
    volumes:
      - ${JF_MEDIA}:/media
      - ${JF_CONFIG}:/config
      - ${JF_CACHE}:/cache

