version: "3"

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    # ports:
    #   - 8096:8096
    environment:
      - TZ=America/Santiago
    volumes:
      - ${MEDIA_STORAGE}:/media
      - ${JF_CONFIG}:/config
      - ${JF_CACHE}:/cache
    network_mode: "host"

  transmission:
    image: linuxserver/transmission
    command: transmission-daemon -f -g /config
    restart: unless-stopped
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    environment:
      - TZ=America/Santiago
    volumes:
      - ./transmission/config.json:/config/config.json
      - ${TRANSMISSION_CONFIG}:/config
      - ${TORRENT_STORAGE}:/downloads

  flexget:
    image: wiserain/flexget:3.3.4
    restart: unless-stopped
    ports:
      - 5050:5050
    expose:
      - 5050
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Santiago
      - TORRENT_PLUGIN=transmission
      - FG_WEBUI_PASSWD=${FG_PASS}
    volumes:
      - ./flexget/custom-cont-init.d/:/config/custom-cont-init.d/
      - ./flexget/config.yml:/config/config.yml
      - ${FG_CONFIG}:/config
      - ${TORRENT_STORAGE}:/downloads
      - ${MEDIA_STORAGE}:/storage
    links:
      - transmission
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      - TZ="America/Santiago"
      - WEBPASSWORD=${PH_PASS}
    volumes:
      - ./etc-pihole/:/etc/pihole/
      - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
# networks:
#   lan:
#     driver: macvlan
#     driver_opts:
#       parent: eth0
#     ipam:
#       config:
#         - subnet: "192.168.100.129/24"
#           gateway: "192.168.100.1"
