version: "3"

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    environment:
      - TZ=America/Santiago
    volumes:
      - ${MEDIA_STORAGE}:/media
      - ${JF_CONFIG}:/config
      - ${JF_CACHE}:/cache
    network_mode: "host"

  transmission:
    image: linuxserver/transmission
    command: transmission-daemon -f -g /config
    restart: unless-stopped
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    environment:
      - TZ=America/Santiago
    volumes:
      - ./transmission/config.json:/config/config.json
      - ${TRANSMISSION_CONFIG}:/config
      - ${TORRENT_STORAGE}:/downloads

  flexget:
    image: wiserain/flexget:3.3.4
    restart: on-failure:2
    ports:
      - 5050:5050
    expose:
      - 5050
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Santiago
      - TORRENT_PLUGIN=transmission
      - FG_WEBUI_PASSWD=${FG_PASS}
    volumes:
      - ./flexget/custom-cont-init.d/:/config/custom-cont-init.d/
      - ./flexget/config.yml:/config/config.yml
      - ./flexget/secrets.yml:/config/secrets.yml
      - ./flexget/anime.yml:/config/anime.yml
      - ${FG_CONFIG}:/config
      - ${TORRENT_STORAGE}:/downloads
      - ${MEDIA_STORAGE}:/storage
    links:
      - transmission

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Tashkent
    ports:
      - 5055:5055
    restart: unless-stopped
    links:
      - jellyfin
