variables: secrets.yml

web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes
  base_url: /flexget

schedules:
  - tasks: "*"
    interval:
      minutes: 30

templates:
  anime:
    quality: 720p
    include: anime.yml
  transmission-settings:
    transmission:
      host: "{? transmission.host ?}"
      port: "{? transmission.port ?}"
      username: "{? transmission.username ?}"
      password: "{? transmission.password ?}"

tasks:
  rss-nyaa-pubsubs:
    rss: https://nyaa.si/?page=rss&c=0_0&f=0&q=puyasubs%21
    priority: 1
    no_entries_ok: yes
    template:
      - anime
      - transmission-settings
  move-anime:
    priority: 2
    no_entries_ok: yes
    parsing:
      series: guessit
    filesystem:
      path: /downloads/complete
      recursive: yes
    accept_all: yes
    imdb_lookup: yes
    require_field: series_name
    all_series:
      parse_only: yes
    move:
      to: "/storage/anime/{{imdb_name}}"
      rename: "{{imdb_name}}-{{imdb}}{{ location|pathext }}"
      along:
        extensions:
          - sub
          - srt
        subdirs:
          - Subs
    # exec:
    #   auto_escape: yes
    #   on_output:
    #     for_entries: |
    #       mkdir -p "/storage/anime/{{ imdb_name }}" && mv "{{ location }}" "/storage/anime/{{ imdb_name }}/{{ imdb_name }}-{{ imdb_id }}{{ location | pathext }}"
  # remove_stale_torrents:
  #   from_transmission:
  #     host: "{? transmission.host ?}"
  #     port: "{? transmission.port ?}"
  #     username: "{? transmission.username ?}"
  #     password: "{? transmission.password ?}"
  #   disable: [seen, seen_info_hash]
  #   if:
  #     - transmission_progress == 100: accept
  #     - not transmission_seed_ratio_ok: reject
  #     - not transmission_idle_limit_ok: reject
  #   transmission:
  #     host: "{? transmission.host ?}"
  #     port: "{? transmission.port ?}"
  #     username: "{? transmission.username ?}"
  #     password: "{? transmission.password ?}"
  #     action: purge
